language: ruby
cache:    bundler
script:   bundle exec rake test
sudo:     false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
  - jruby-9.2.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
