language: ruby
cache:    bundler
script:   rake test
sudo:     false

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0
  - ruby-head
  - jruby-9.2.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
